### ISSUE TITLE
"My reservations" page

### ISSUE THREAD

**Issue by MindChirp** [TIHLDE/kontres#16]
Perhaps create a "My reservations" page, where the user can view all pending, declined and granted reservation requests. The user can be redirected to this page once a reservation application form has been submitted successfully.

**Comment by ConradOsvik** [comment]
hva er status på denne? mekker du @MindChirp ? vi må også legge til at man kan redigere søknader ref sober watch men også for denne siden

**Comment by MindChirp** [comment]
@ConradOsvik jeg tenker at all redigering skjer på samme side, så hvis man ønsker å reservere en reservasjon man har på "my reservations", så sendes man videre til en felles redigeringsside

**Comment by MindChirp** [comment]
Tenkte å ta en titt på denne i dag, så det er nok klart til mandag
