### ISSUE TITLE
format date prettier

### ISSUE THREAD

**Issue by eriskjel** [TIHLDE/kontres#70]
![image](https://github.com/TIHLDE/kontresv2/assets/98759397/f4b2ef81-6f64-487b-8164-27258038bb3b)

date is hard to read. can we make it more pretty pls

**Comment by MindChirp** [comment]
Umulig.

**Comment by eriskjel** [comment]
![image](https://github.com/TIHLDE/kontresv2/assets/98759397/3a519691-9447-4c9c-83a9-c80338871b45)

**Comment by MindChirp** [comment]
personangrep? 🤔
