### ISSUE TITLE
add approved by field 

### ISSUE THREAD

**Issue by eriskjel** [TIHLDE/kontres#75]
add a field to see who approved a reservation

backend progress:
https://github.com/TIHLDE/Lepton/pull/786

**Comment by MindChirp** [comment]
🥲

**Comment by eriskjel** [comment]
denne er ferdig?

**Comment by MindChirp** [comment]
Ja, men har ikke lagt inn pr

**Comment by MindChirp** [comment]
Kan du sende hele brukerobjektet? 😇

**Comment by eriskjel** [comment]
gjør jeg ikke det da?

**Comment by eriskjel** [comment]
jeg gjør jo det

**Comment by eriskjel** [comment]
er denne good @MindChirp

**Comment by MindChirp** [comment]
Jeg tror det skal funke i frontend hvis hele brukerobjektet sendes fra backend. Jeg har iallefall implementert alt, så issuet er basically ferdig

**Comment by eriskjel** [comment]
sendes ikke hele brukerobjektet? tror det gjør det? @MindChirp

**Comment by MindChirp** [comment]
Kan godt hende, er en stund siden jeg gjorde det sist. Ligger det i prod, tror du?
