### ISSUE TITLE
Allow undefined sober watch

### ISSUE THREAD

**Issue by MindChirp** [TIHLDE/kontres#79]
The sober watch dropdown should have an option for "Ikke bestemt enda". The applicant(s) should then be able to edit the request at a later time, and set the sober watch.

**Comment by ConradOsvik** [comment]
kanskje mer naturlig med at den autofyller inn innlogget bruker? blir det ikke et loophole om man kan la det stå tomt? @MindChirp

**Comment by eriskjel** [comment]
blir evt å implementere notifikasjonssystem og evt Deny'e reservasjonen dersom edruvakt ikke blir valgt innen xx:xx. litt mye jobb for lite feature spør dere meg

**Comment by Daniel-AVE** [comment]
Er ikke noe nødvendig å måtte deny'e en reservasjon om det ikke blir lagt inn. Er egentlig ikke så alt for viktig for kontoret å vite om de har fått tak i edruvakt eller ikke. Viktigste er at de husker på at de må søke alkoholtillatelse hos NTNU, og de trenger å vite edruvakt
