### ISSUE TITLE
Problem with "sort by start-time"

### ISSUE THREAD

**Issue by Daniel-AVE** [TIHLDE/kontres#85]
When a user tries to sort reservations by "start"-time in the admin-page, it looks like the "start"-time is only taking the date of the month into account, and not the month. This makes it so a reservation happening on the 3rd in over 1 month, comes before reservations happening in 10 days.

**Comment by eriskjel** [comment]
er dette backend eller frontend @MindChirp

**Comment by MindChirp** [comment]
Frontend hehe

**Comment by Daniel-AVE** [comment]
På samme ting:
Er det mulig å få til å benytte "flere filtre" samtidig? Eksempelvis sortere på "gjenstand" og "start" samtidig? Hadde vært nice for eksempel å kunne sortere slik at jeg ser kontoret, og så kunne sortere på dato etter det for å enkelt kunne få oversikt over når kontoret er booka

**Comment by MindChirp** [comment]
> På samme ting: Er det mulig å få til å benytte "flere filtre" samtidig? Eksempelvis sortere på "gjenstand" og "start" samtidig? Hadde vært nice for eksempel å kunne sortere slik at jeg ser kontoret, og så kunne sortere på dato etter det for å enkelt kunne få oversikt over når kontoret er booka

Det er egt litt stress, men hvis du føler det er nødvendig kan du opprette et eget issue for det
