### ISSUE TITLE
FAQ/Wiki/Help-page to display important information

### ISSUE THREAD

**Issue by Daniel-AVE** [TIHLDE/kontres#87]
Currently, there is a link shown when booking the office, and checking of the "alcohol" box. Instead of making this reservation-page more complex, it would be nice with a stand-alone "page" on the site, where important information could be added. Perhaps then with a possibility for an admin to create new "posts" in the page, similar to how the Wiki works on the TIHLDE-page. 

One of the most important areas to be able to add information for is regarding the application for drinking alchol on campus to NTNU, including when an application should be sent in, what information does it need, and an example of a filled out form. 

Open for discussion or other ideas to incorporate this

**Comment by Embretr** [comment]
@eriskjel si ifra om du har tid til denne så kan jeg starte på frontend

**Comment by eriskjel** [comment]
@Embretr denna er litt sidequest for min del vertfall. virker som mer frontend enn backend uans, så du må bare starte

**Comment by MindChirp** [comment]
@Embretr hvor ligger du an på denne?

**Comment by MindChirp** [comment]
Det er laga et nytt issue for denne #103
