### ISSUE TITLE
IMPORTANT! Bug: When hovering over a calendar, the time that shows up is only a 12 hour clock. 

### ISSUE THREAD

**Issue by Daniel-AVE** [TIHLDE/kontres#91]
Even when trying to drag time-slots from 20:00 one day to 15:00 another day, it automatically sets 8am as start point and 3am for end-point.

**Comment by Daniel-AVE** [comment]
Oppdatering:

Ser ut til at det som skjer er at når den pop-upen av tidspunkt som er låst til hvor musa er beveger seg, så oppdaterer tall seg. Men når man scroller ned med musehjulet, så oppdaterer den seg ikke, og fortsetter hvor den slapp. Mao: Om du hovera over 12:00 og blar ned til et punkt hvor det står 20:00, så vil hoveren enda vise 12:00 og fortsette derfra

**Comment by MindChirp** [comment]
@Daniel-AVE Kan du sjekke om dette fortsatt er en bug? Klarer ikke å gjenskape det. Hvis det ikke er et problem lenger så får du lov til å close dette issuet 👌

**Comment by Daniel-AVE** [comment]
@MindChirp Oi, trodde Embret lukka issues når han merget endringer inn jeg. Det ble fiksa ja, så ikke lenger en bug!
